### ISSUE TITLE
Enable/disable Examine content app through appsettings

### ISSUE THREAD

**Issue by creativesuspects** [abjerner/Limbo.Umbraco.Iddqd#1]
It would be great if the Examine content app could be enabled/disabled through the appsettings. Or even better, if the content app could be enabled/disabled for specific document types.

When the Examine content app is activated on a document type without any property tabs the Name-field in the header is not accessible. You have to manually switch to the Info content app to be able to edit the Name-field. This is very confusing for the editors.

**Comment by abjerner** [comment]
Hi @creativesuspects 

Sorry for the lack of reply - I haven't really worked on the package for a while, and missed this issue.

I've pushed some new release, so if you update to the newest version, the content app has been renamed to **Iddqd**, and has a weight higher than Umbraco's default **Info** app, meaning that you should no longer experience the issue.

It's still not possible to disable the content app through your app settings though.

**Comment by creativesuspects** [comment]
Thanks! That really helps.
